ingressClassName: nginx
host: ""

paths:
  ships:
    prefix: /api/ships
    serviceName: ship-service
    servicePort: 8081

  components:
    prefix: /api/components
    serviceName: component-service
    servicePort: 8082

  auth:
    prefix: /api/auth
    serviceName: auth-service
    servicePort: 8083

  frontend:
    prefix: /
    serviceName: frontend
    servicePort: 80