ingressClassName: nginx
host: ""

paths:
  ships:
    prefix: /api
    serviceName: ship-service
    servicePort: 8081

  components:
    prefix: /api
    serviceName: component-service
    servicePort: 8082
