apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship-service
  template:
    metadata:
      labels:
        app: ship-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: ship-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
{{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
{{- end }}
