apiVersion: v1
kind: Secret
metadata:
  name: ship-service-db
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  APP_JWT_SECRET: {{ .Values.jwt.shared | quote }}

