apiVersion: v1
kind: Service
metadata:
  name: ship-service
spec:
  selector:
    app.kubernetes.io/name: ship-service
    app.kubernetes.io/instance: ship-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
