replicaCount: 1

image:
  repository: ghcr.io/rso-simon/auth-service
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: ghcr-secret

service:
  type: ClusterIP
  port: 8083

probes:
  livenessPath: /api/auth/actuator/health/liveness
  readinessPath: /api/auth/actuator/health/readiness

db:
  host: postgres
  port: 5432
  name: appdb
  username: postgres
  password: pass

server:
  contextPath: /api/auth

jwt:
  tll: 3600
  shared: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

resources: {}