replicaCount: 1

image:
  repository: ghcr.io/rso-simon/component-service
  tag: ""                 # set by workflow via --set image.tag=<sha>
  pullPolicy: IfNotPresent
  pullSecret: ghcr-secret

service:
  type: ClusterIP
  port: 8082

#env:
#  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
#  SPRING_DATASOURCE_USERNAME: postgres
#  SPRING_DATASOURCE_PASSWORD: pass
#  SERVER_FORWARD_HEADERS_STRATEGY: native
#  SERVER_SERVLET_CONTEXT_PATH: /api/components

probes:
  livenessPath: /api/components/actuator/health/liveness
  readinessPath: /api/components/actuator/health/readiness

db:
  host: postgres
  port: 5432
  name: appdb
  username: postgres
  password: pass

server:
  contextPath: /api/components

resources: {}
