apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rso-services
  namespace: rso
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - {{- if .Values.host }}host: {{ .Values.host | quote }}{{- end }}
      http:
        paths:
          - path: {{ .Values.paths.ships.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.paths.ships.serviceName }}
                port:
                  number: {{ .Values.paths.ships.servicePort }}

          - path: {{ .Values.paths.components.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.paths.components.serviceName }}
                port:
                  number: {{ .Values.paths.components.servicePort }}

          - path: {{ .Values.paths.auth.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.paths.auth.serviceName }}
                port:
                  number: {{ .Values.paths.auth.servicePort }}
