apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: component-service
  template:
    metadata:
      labels:
        app: component-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: component-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/api/components"

