apiVersion: v1
kind: Service
metadata:
  name: component-service
spec:
  selector:
    app: component-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
